server:
  port: 8081

---

spring:
  profiles: default
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:29092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: contract-service
          destination: contract-service
          contentType: application/json
        event-out:
          destination: contract-service
          contentType: application/json
  datasource:
    url: jdbc:mysql://localhost:3306/tes
    username: root
    password: admin
    driverClassName: com.mysql.cj.jdbc.Driver

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug

---

server:
  port: 8080

spring:
  profiles: docker
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: contract-service
          destination: contract-service
          contentType: application/json
        event-out:
          destination: contract-service
          contentType: application/json